### ISSUE TITLE
Part of the codes are uploaded!

### ISSUE THREAD

**Issue by yuxin0406** [naturalis/trait-behavioral-ungulates#1]
@rvosa These files were uploaded by mobile phone, have not been sorted yet☹️ Because the eduvpn was unstable these days and cannot be opened at all today. I will wait a few more days to see if I need to change it.

**Comment by rvosa** [comment]
Ok! I guess you don't need the eduvpn though? Github is not part of naturalis.

**Comment by rvosa** [comment]
[Model_Selection_Num.R](https://github.com/naturalis/trait-behavioral-ungulates/blob/main/How%20does%20ecology%20predict%20ungulate%20traits.Rmd#L152) seems to be missing?
